# Generated by Django 4.2.8 on 2023-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
