# Generated by Django 4.2.8 on 2023-12-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appueu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='batoniha',
        ),
    ]
