# Generated by Django 4.2.8 on 2023-12-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appueu', '0002_delete_batoniha'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatel',
            name='coin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
